name: mynewapp
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  confetti: ^0.8.0
  flutter_animate: ^4.5.2
  google_fonts: ^6.2.1
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/pokedex/sprites/
    - images/pokedex/hires/
    - images/pokedex/
    - images/
    - tcg_data/
